// This file is generated by ZCL Advanced Platform generator. Please don't edit manually.

// The following is brought in by the endianness component, which all
// applications must include
#include "sl_endianness.h"

#ifndef SILABS_AF_ENDPOINT_CONFIG
#define SILABS_AF_ENDPOINT_CONFIG 1

// Default values for the attributes longer than a pointer, in a form of a
// binary blob. All attribute values with size greater than 2 bytes. Excluding 0
// values and externally saved values. Separate block is generated for
// big-endian and little-endian cases.

#define ZCL_GENERATED_DEFAULTS_COUNT (2)

#if BIGENDIAN_CPU
#define ZCL_GENERATED_DEFAULTS { \
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, /* 0,DEFAULT value for cluster: Over the Air Bootloading, attribute: OTA Upgrade Server ID, side: client */ \
  0xFF, 0xFF, 0xFF, 0xFF, /* 8,DEFAULT value for cluster: Over the Air Bootloading, attribute: Offset (address) into the file, side: client */ \
}
#else //!BIGENDIAN_CPU
#define ZCL_GENERATED_DEFAULTS { \
  0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, /* 0,DEFAULT value for cluster: Over the Air Bootloading, attribute: OTA Upgrade Server ID, side: client */ \
  0xFF, 0xFF, 0xFF, 0xFF, /* 8,DEFAULT value for cluster: Over the Air Bootloading, attribute: Offset (address) into the file, side: client */ \
}
#endif


// This is an array of sl_zigbee_af_attribute_min_max_value_t structures.

#define ZCL_GENERATED_MIN_MAX_DEFAULT_COUNT (0)
	#define ZCL_GENERATED_MIN_MAX_DEFAULTS { { { .ptrToDefaultValue = (uint8_t*)0x00 }, { .ptrToDefaultValue = (uint8_t*)0x00 }, { .ptrToDefaultValue = (uint8_t*)0x00 } } }


#define ZCL_GENERATED_ATTRIBUTE_COUNT (44)

// This is an array of sl_zigbee_af_attribute_metadata_t structures.
#define ZCL_GENERATED_ATTRIBUTES { \
  { 0x0000, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0x08  } }, /* 0 Cluster: Basic, Attribute: ZCL version, Side: server*/ \
		  { 0x0001, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0x00  } }, /* 1 Cluster: Basic, Attribute: application version, Side: server*/ \
		  { 0x0002, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0x00  } }, /* 2 Cluster: Basic, Attribute: stack version, Side: server*/ \
		  { 0x0003, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0x00  } }, /* 3 Cluster: Basic, Attribute: hardware version, Side: server*/ \
		  { 0x0004, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 33, (0x00), { NULL } }, /* 4 Cluster: Basic, Attribute: manufacturer name, Side: server*/ \
	  { 0x0005, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 33, (0x00), { NULL } }, /* 5 Cluster: Basic, Attribute: model identifier, Side: server*/ \
	  { 0x0006, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 17, (0x00), { NULL } }, /* 6 Cluster: Basic, Attribute: date code, Side: server*/ \
	  { 0x0007, ZCL_ENUM8_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0x00  } }, /* 7 Cluster: Basic, Attribute: power source, Side: server*/ \
		  { 0x0008, ZCL_ENUM8_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0xFF  } }, /* 8 Cluster: Basic, Attribute: generic device class, Side: server*/ \
		  { 0x0009, ZCL_ENUM8_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0xFF  } }, /* 9 Cluster: Basic, Attribute: generic device type, Side: server*/ \
		  { 0x000A, ZCL_OCTET_STRING_ATTRIBUTE_TYPE, 17, (0x00), { NULL } }, /* 10 Cluster: Basic, Attribute: product code, Side: server*/ \
	  { 0x000B, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 65, (0x00), { NULL } }, /* 11 Cluster: Basic, Attribute: product url, Side: server*/ \
	  { 0x4000, ZCL_CHAR_STRING_ATTRIBUTE_TYPE, 17, (0x00), { NULL } }, /* 12 Cluster: Basic, Attribute: sw build id, Side: server*/ \
	  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)3  } }, /* 13 Cluster: Basic, Attribute: cluster revision, Side: server*/ \
		  { 0x0000, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE), { (uint8_t*)0  } }, /* 14 Cluster: Identify, Attribute: identify time, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)5  } }, /* 15 Cluster: Identify, Attribute: cluster revision, Side: server*/ \
		  { 0x0000, ZCL_BITMAP8_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0  } }, /* 16 Cluster: Groups, Attribute: name support, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)3  } }, /* 17 Cluster: Groups, Attribute: cluster revision, Side: server*/ \
		  { 0x0000, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0x00  } }, /* 18 Cluster: Scenes, Attribute: scene count, Side: server*/ \
		  { 0x0001, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0x00  } }, /* 19 Cluster: Scenes, Attribute: current scene, Side: server*/ \
		  { 0x0002, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)0x0000  } }, /* 20 Cluster: Scenes, Attribute: current group, Side: server*/ \
		  { 0x0003, ZCL_BOOLEAN_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0x00  } }, /* 21 Cluster: Scenes, Attribute: scene valid, Side: server*/ \
		  { 0x0004, ZCL_BITMAP8_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0x00  } }, /* 22 Cluster: Scenes, Attribute: name support, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)3  } }, /* 23 Cluster: Scenes, Attribute: cluster revision, Side: server*/ \
		  { 0x0000, ZCL_BOOLEAN_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0x00  } }, /* 24 Cluster: On/off, Attribute: on/off, Side: server*/ \
		  { 0x4000, ZCL_BOOLEAN_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)0x01  } }, /* 25 Cluster: On/off, Attribute: global scene control, Side: server*/ \
		  { 0x4001, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE), { (uint8_t*)0x0000  } }, /* 26 Cluster: On/off, Attribute: on time, Side: server*/ \
		  { 0x4002, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE), { (uint8_t*)0x0000  } }, /* 27 Cluster: On/off, Attribute: off wait time, Side: server*/ \
		  { 0x4003, ZCL_ENUM8_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE), { (uint8_t*)0x00  } }, /* 28 Cluster: On/off, Attribute: start up on off, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)2  } }, /* 29 Cluster: On/off, Attribute: cluster revision, Side: server*/ \
		  { 0x0000, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (0x00), { (uint8_t*)1  } }, /* 30 Cluster: Level Control, Attribute: current level, Side: server*/ \
		  { 0x0001, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)0  } }, /* 31 Cluster: Level Control, Attribute: remaining time, Side: server*/ \
		  { 0x000F, ZCL_BITMAP8_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE), { (uint8_t*)0  } }, /* 32 Cluster: Level Control, Attribute: options, Side: server*/ \
		  { 0x0010, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE), { (uint8_t*)0  } }, /* 33 Cluster: Level Control, Attribute: on off transition time, Side: server*/ \
		  { 0x0012, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE), { (uint8_t*)0  } }, /* 34 Cluster: Level Control, Attribute: on transition time, Side: server*/ \
		  { 0x0013, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_WRITABLE), { (uint8_t*)0  } }, /* 35 Cluster: Level Control, Attribute: off transition time, Side: server*/ \
		  { 0x0014, ZCL_INT8U_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_WRITABLE), { (uint8_t*)0  } }, /* 36 Cluster: Level Control, Attribute: default move rate, Side: server*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)3  } }, /* 37 Cluster: Level Control, Attribute: cluster revision, Side: server*/ \
		  { 0x0000, ZCL_IEEE_ADDRESS_ATTRIBUTE_TYPE, 8, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)&(generatedDefaults[0]) } }, /* 38 Cluster: Over the Air Bootloading, Attribute: OTA Upgrade Server ID, Side: client*/ \
	  { 0x0001, ZCL_INT32U_ATTRIBUTE_TYPE, 4, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)&(generatedDefaults[8]) } }, /* 39 Cluster: Over the Air Bootloading, Attribute: Offset (address) into the file, Side: client*/ \
	  { 0x0006, ZCL_ENUM8_ATTRIBUTE_TYPE, 1, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)0x00  } }, /* 40 Cluster: Over the Air Bootloading, Attribute: OTA Upgrade Status, Side: client*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)4  } }, /* 41 Cluster: Over the Air Bootloading, Attribute: cluster revision, Side: client*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (ATTRIBUTE_MASK_CLIENT), { (uint8_t*)2  } }, /* 42 Cluster: Occupancy Sensing, Attribute: cluster revision, Side: client*/ \
		  { 0xFFFD, ZCL_INT16U_ATTRIBUTE_TYPE, 2, (0x00), { (uint8_t*)0x0001  } } /* 43 Cluster: ZLL Commissioning, Attribute: cluster revision, Side: server*/ \
		 }

 

#define ZCL_GENERATED_CLUSTER_COUNT (9)
	
// This is an array of sl_zigbee_af_cluster_t structures.
#define ZCL_GENERATED_CLUSTERS { \
  { 0x0000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[0]), 14, 191, CLUSTER_MASK_SERVER, NULL }, /* 0, Endpoint Id: 1, Cluster: Basic, Side: server*/ \
	  { 0x0003, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[14]), 2, 4, CLUSTER_MASK_SERVER, NULL }, /* 1, Endpoint Id: 1, Cluster: Identify, Side: server*/ \
	  { 0x0004, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[16]), 2, 3, CLUSTER_MASK_SERVER, NULL }, /* 2, Endpoint Id: 1, Cluster: Groups, Side: server*/ \
	  { 0x0005, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[18]), 6, 8, CLUSTER_MASK_SERVER, NULL }, /* 3, Endpoint Id: 1, Cluster: Scenes, Side: server*/ \
	  { 0x0006, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[24]), 6, 9, CLUSTER_MASK_SERVER, NULL }, /* 4, Endpoint Id: 1, Cluster: On/off, Side: server*/ \
	  { 0x0008, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[30]), 8, 13, CLUSTER_MASK_SERVER, NULL }, /* 5, Endpoint Id: 1, Cluster: Level Control, Side: server*/ \
	  { 0x0019, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[38]), 4, 15, CLUSTER_MASK_CLIENT, NULL }, /* 6, Endpoint Id: 1, Cluster: Over the Air Bootloading, Side: client*/ \
	  { 0x0406, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[42]), 1, 2, CLUSTER_MASK_CLIENT, NULL }, /* 7, Endpoint Id: 1, Cluster: Occupancy Sensing, Side: client*/ \
	  { 0x1000, (sl_zigbee_af_attribute_metadata_t*)&(generatedAttributes[43]), 1, 2, CLUSTER_MASK_SERVER, NULL } /* 8, Endpoint Id: 1, Cluster: ZLL Commissioning, Side: server*/ \
	 }

 
#define ZCL_GENERATED_ENDPOINT_TYPE_COUNT (1)

// This is an array of sl_zigbee_af_endpoint_type_t structures.
#define ZCL_GENERATED_ENDPOINT_TYPES { \
  { ((sl_zigbee_af_cluster_t*)&(generatedClusters[0])), 9, 247 }, \
	 } 
// Largest attribute size is needed for various buffers
#define ZCL_ATTRIBUTE_LARGEST (65)

// Total size of singleton attributes
#define ZCL_ATTRIBUTE_SINGLETONS_SIZE (0)

// Total size of attribute storage
#define ZCL_ATTRIBUTE_MAX_SIZE (247)

// Number of fixed endpoints	
#define ZCL_FIXED_ENDPOINT_COUNT (1)

// Array of endpoints that are supported, the data inside the array is the
// endpoint number.
#define ZCL_FIXED_ENDPOINT_ARRAY { \
  1 \
}

// Array of profile ids
#define ZCL_FIXED_PROFILE_IDS { \
  260 \
}

// Array of device ids
#define ZCL_FIXED_DEVICE_IDS { \
  257 \
}

// Array of device versions
#define ZCL_FIXED_DEVICE_VERSIONS { \
  3 \
}

// Array of endpoint types supported on each endpoint
#define ZCL_FIXED_ENDPOINT_TYPES { \
  0 \
}

// Array of networks supported on each endpoint
#define ZCL_FIXED_NETWORKS { \
  0 \
}

// Array of sl_zigbee_af_command_metadata_t structs.
#define ZCL_ZAP_COMMAND_MASK(mask) COMMAND_MASK_ ## mask
#define SL_ZIGBEE_ZCL_GENERATED_COMMAND_COUNT  (69)
#define ZCL_GENERATED_COMMANDS { \
  { 0x0003, 0x00, COMMAND_MASK_INCOMING_SERVER }, /* 0, Cluster: Identify, Command: Identify*/ \
	  { 0x0003, 0x00, COMMAND_MASK_OUTGOING_SERVER }, /* 1, Cluster: Identify, Command: IdentifyQueryResponse*/ \
	  { 0x0003, 0x01, COMMAND_MASK_INCOMING_SERVER }, /* 2, Cluster: Identify, Command: IdentifyQuery*/ \
	  { 0x0003, 0x40, COMMAND_MASK_INCOMING_SERVER }, /* 3, Cluster: Identify, Command: TriggerEffect*/ \
	  { 0x0004, 0x00, COMMAND_MASK_INCOMING_SERVER }, /* 4, Cluster: Groups, Command: AddGroup*/ \
	  { 0x0004, 0x00, COMMAND_MASK_OUTGOING_SERVER }, /* 5, Cluster: Groups, Command: AddGroupResponse*/ \
	  { 0x0004, 0x01, COMMAND_MASK_INCOMING_SERVER }, /* 6, Cluster: Groups, Command: ViewGroup*/ \
	  { 0x0004, 0x01, COMMAND_MASK_OUTGOING_SERVER }, /* 7, Cluster: Groups, Command: ViewGroupResponse*/ \
	  { 0x0004, 0x02, COMMAND_MASK_INCOMING_SERVER }, /* 8, Cluster: Groups, Command: GetGroupMembership*/ \
	  { 0x0004, 0x02, COMMAND_MASK_OUTGOING_SERVER }, /* 9, Cluster: Groups, Command: GetGroupMembershipResponse*/ \
	  { 0x0004, 0x03, COMMAND_MASK_INCOMING_SERVER }, /* 10, Cluster: Groups, Command: RemoveGroup*/ \
	  { 0x0004, 0x03, COMMAND_MASK_OUTGOING_SERVER }, /* 11, Cluster: Groups, Command: RemoveGroupResponse*/ \
	  { 0x0004, 0x04, COMMAND_MASK_INCOMING_SERVER }, /* 12, Cluster: Groups, Command: RemoveAllGroups*/ \
	  { 0x0004, 0x05, COMMAND_MASK_INCOMING_SERVER }, /* 13, Cluster: Groups, Command: AddGroupIfIdentifying*/ \
	  { 0x0005, 0x00, COMMAND_MASK_INCOMING_SERVER }, /* 14, Cluster: Scenes, Command: AddScene*/ \
	  { 0x0005, 0x00, COMMAND_MASK_OUTGOING_SERVER }, /* 15, Cluster: Scenes, Command: AddSceneResponse*/ \
	  { 0x0005, 0x01, COMMAND_MASK_INCOMING_SERVER }, /* 16, Cluster: Scenes, Command: ViewScene*/ \
	  { 0x0005, 0x01, COMMAND_MASK_OUTGOING_SERVER }, /* 17, Cluster: Scenes, Command: ViewSceneResponse*/ \
	  { 0x0005, 0x02, COMMAND_MASK_INCOMING_SERVER }, /* 18, Cluster: Scenes, Command: RemoveScene*/ \
	  { 0x0005, 0x02, COMMAND_MASK_OUTGOING_SERVER }, /* 19, Cluster: Scenes, Command: RemoveSceneResponse*/ \
	  { 0x0005, 0x03, COMMAND_MASK_INCOMING_SERVER }, /* 20, Cluster: Scenes, Command: RemoveAllScenes*/ \
	  { 0x0005, 0x03, COMMAND_MASK_OUTGOING_SERVER }, /* 21, Cluster: Scenes, Command: RemoveAllScenesResponse*/ \
	  { 0x0005, 0x04, COMMAND_MASK_INCOMING_SERVER }, /* 22, Cluster: Scenes, Command: StoreScene*/ \
	  { 0x0005, 0x04, COMMAND_MASK_OUTGOING_SERVER }, /* 23, Cluster: Scenes, Command: StoreSceneResponse*/ \
	  { 0x0005, 0x05, COMMAND_MASK_INCOMING_SERVER }, /* 24, Cluster: Scenes, Command: RecallScene*/ \
	  { 0x0005, 0x06, COMMAND_MASK_INCOMING_SERVER }, /* 25, Cluster: Scenes, Command: GetSceneMembership*/ \
	  { 0x0005, 0x06, COMMAND_MASK_OUTGOING_SERVER }, /* 26, Cluster: Scenes, Command: GetSceneMembershipResponse*/ \
	  { 0x0005, 0x40, COMMAND_MASK_INCOMING_SERVER }, /* 27, Cluster: Scenes, Command: EnhancedAddScene*/ \
	  { 0x0005, 0x41, COMMAND_MASK_INCOMING_SERVER }, /* 28, Cluster: Scenes, Command: EnhancedViewScene*/ \
	  { 0x0005, 0x42, COMMAND_MASK_INCOMING_SERVER }, /* 29, Cluster: Scenes, Command: CopyScene*/ \
	  { 0x0006, 0x00, COMMAND_MASK_INCOMING_SERVER }, /* 30, Cluster: On/off, Command: Off*/ \
	  { 0x0006, 0x01, COMMAND_MASK_INCOMING_SERVER }, /* 31, Cluster: On/off, Command: On*/ \
	  { 0x0006, 0x02, COMMAND_MASK_INCOMING_SERVER }, /* 32, Cluster: On/off, Command: Toggle*/ \
	  { 0x0006, 0x40, COMMAND_MASK_INCOMING_SERVER }, /* 33, Cluster: On/off, Command: OffWithEffect*/ \
	  { 0x0006, 0x41, COMMAND_MASK_INCOMING_SERVER }, /* 34, Cluster: On/off, Command: OnWithRecallGlobalScene*/ \
	  { 0x0006, 0x42, COMMAND_MASK_INCOMING_SERVER }, /* 35, Cluster: On/off, Command: OnWithTimedOff*/ \
	  { 0x0008, 0x00, COMMAND_MASK_INCOMING_SERVER }, /* 36, Cluster: Level Control, Command: MoveToLevel*/ \
	  { 0x0008, 0x01, COMMAND_MASK_INCOMING_SERVER }, /* 37, Cluster: Level Control, Command: Move*/ \
	  { 0x0008, 0x02, COMMAND_MASK_INCOMING_SERVER }, /* 38, Cluster: Level Control, Command: Step*/ \
	  { 0x0008, 0x03, COMMAND_MASK_INCOMING_SERVER }, /* 39, Cluster: Level Control, Command: Stop*/ \
	  { 0x0008, 0x04, COMMAND_MASK_INCOMING_SERVER }, /* 40, Cluster: Level Control, Command: MoveToLevelWithOnOff*/ \
	  { 0x0008, 0x05, COMMAND_MASK_INCOMING_SERVER }, /* 41, Cluster: Level Control, Command: MoveWithOnOff*/ \
	  { 0x0008, 0x06, COMMAND_MASK_INCOMING_SERVER }, /* 42, Cluster: Level Control, Command: StepWithOnOff*/ \
	  { 0x0008, 0x07, COMMAND_MASK_INCOMING_SERVER }, /* 43, Cluster: Level Control, Command: StopWithOnOff*/ \
	  { 0x0019, 0x00, COMMAND_MASK_INCOMING_CLIENT }, /* 44, Cluster: Over the Air Bootloading, Command: ImageNotify*/ \
	  { 0x0019, 0x01, COMMAND_MASK_OUTGOING_CLIENT }, /* 45, Cluster: Over the Air Bootloading, Command: QueryNextImageRequest*/ \
	  { 0x0019, 0x02, COMMAND_MASK_INCOMING_CLIENT }, /* 46, Cluster: Over the Air Bootloading, Command: QueryNextImageResponse*/ \
	  { 0x0019, 0x03, COMMAND_MASK_OUTGOING_CLIENT }, /* 47, Cluster: Over the Air Bootloading, Command: ImageBlockRequest*/ \
	  { 0x0019, 0x05, COMMAND_MASK_INCOMING_CLIENT }, /* 48, Cluster: Over the Air Bootloading, Command: ImageBlockResponse*/ \
	  { 0x0019, 0x06, COMMAND_MASK_OUTGOING_CLIENT }, /* 49, Cluster: Over the Air Bootloading, Command: UpgradeEndRequest*/ \
	  { 0x0019, 0x07, COMMAND_MASK_INCOMING_CLIENT }, /* 50, Cluster: Over the Air Bootloading, Command: UpgradeEndResponse*/ \
	  { 0x1000, 0x00, COMMAND_MASK_INCOMING_SERVER }, /* 51, Cluster: ZLL Commissioning, Command: ScanRequest*/ \
	  { 0x1000, 0x01, COMMAND_MASK_OUTGOING_SERVER }, /* 52, Cluster: ZLL Commissioning, Command: ScanResponse*/ \
	  { 0x1000, 0x02, COMMAND_MASK_INCOMING_SERVER }, /* 53, Cluster: ZLL Commissioning, Command: DeviceInformationRequest*/ \
	  { 0x1000, 0x03, COMMAND_MASK_OUTGOING_SERVER }, /* 54, Cluster: ZLL Commissioning, Command: DeviceInformationResponse*/ \
	  { 0x1000, 0x06, COMMAND_MASK_INCOMING_SERVER }, /* 55, Cluster: ZLL Commissioning, Command: IdentifyRequest*/ \
	  { 0x1000, 0x07, COMMAND_MASK_INCOMING_SERVER }, /* 56, Cluster: ZLL Commissioning, Command: ResetToFactoryNewRequest*/ \
	  { 0x1000, 0x10, COMMAND_MASK_INCOMING_SERVER }, /* 57, Cluster: ZLL Commissioning, Command: NetworkStartRequest*/ \
	  { 0x1000, 0x11, COMMAND_MASK_OUTGOING_SERVER }, /* 58, Cluster: ZLL Commissioning, Command: NetworkStartResponse*/ \
	  { 0x1000, 0x12, COMMAND_MASK_INCOMING_SERVER }, /* 59, Cluster: ZLL Commissioning, Command: NetworkJoinRouterRequest*/ \
	  { 0x1000, 0x13, COMMAND_MASK_OUTGOING_SERVER }, /* 60, Cluster: ZLL Commissioning, Command: NetworkJoinRouterResponse*/ \
	  { 0x1000, 0x14, COMMAND_MASK_INCOMING_SERVER }, /* 61, Cluster: ZLL Commissioning, Command: NetworkJoinEndDeviceRequest*/ \
	  { 0x1000, 0x15, COMMAND_MASK_OUTGOING_SERVER }, /* 62, Cluster: ZLL Commissioning, Command: NetworkJoinEndDeviceResponse*/ \
	  { 0x1000, 0x16, COMMAND_MASK_INCOMING_SERVER }, /* 63, Cluster: ZLL Commissioning, Command: NetworkUpdateRequest*/ \
	  { 0x1000, 0x40, COMMAND_MASK_OUTGOING_SERVER }, /* 64, Cluster: ZLL Commissioning, Command: EndpointInformation*/ \
	  { 0x1000, 0x41, COMMAND_MASK_INCOMING_SERVER }, /* 65, Cluster: ZLL Commissioning, Command: GetGroupIdentifiersRequest*/ \
	  { 0x1000, 0x41, COMMAND_MASK_OUTGOING_SERVER }, /* 66, Cluster: ZLL Commissioning, Command: GetGroupIdentifiersResponse*/ \
	  { 0x1000, 0x42, COMMAND_MASK_INCOMING_SERVER }, /* 67, Cluster: ZLL Commissioning, Command: GetEndpointListRequest*/ \
	  { 0x1000, 0x42, COMMAND_MASK_OUTGOING_SERVER }, /* 68, Cluster: ZLL Commissioning, Command: GetEndpointListResponse*/ \
	 } 
// Array of sl_zigbee_af_manufacturer_code_entry_t structures for commands.
#define ZCL_GENERATED_COMMAND_MANUFACTURER_CODE_COUNT (0)
#define ZCL_GENERATED_COMMAND_MANUFACTURER_CODES { \
  { 0x00, 0x00 }  \
																																																																					 } 
// This is an array of sl_zigbee_af_manufacturer_code_entry_t structures for clusters.
#define ZCL_GENERATED_CLUSTER_MANUFACTURER_CODE_COUNT (0)
#define ZCL_GENERATED_CLUSTER_MANUFACTURER_CODES { \
  { 0x00, 0x00 }  \
									 } 
// This is an array of sl_zigbee_af_manufacturer_code_entry_t structures for attributes.
#define ZCL_GENERATED_ATTRIBUTE_MANUFACTURER_CODE_COUNT (0)
#define ZCL_GENERATED_ATTRIBUTE_MANUFACTURER_CODES { \
  { 0x00, 0x00 } \
																																												 } 
// Array of sl_zigbee_af_plugin_reporting_entry_t structures.
#define SL_ZIGBEE_ZCL_GENERATED_REPORTING_CONFIG_DEFAULTS_TABLE_SIZE (2)
#define SL_ZIGBEE_ZCL_GENERATED_REPORTING_CONFIG_DEFAULTS { \
  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0001, 0x0006, 0x0000, CLUSTER_MASK_SERVER, 0x0000, .data.reported={ 1, 65534, 0 } }, /* Endpoint Id: 1, Cluster: On/off, Attribute: on/off */ \
	  { SL_ZIGBEE_ZCL_REPORTING_DIRECTION_REPORTED, 0x0001, 0x0008, 0x0000, CLUSTER_MASK_SERVER, 0x0000, .data.reported={ 1, 65534, 0 } }, /* Endpoint Id: 1, Cluster: Level Control, Attribute: current level */ \
	 } 

#define SL_ZIGBEE_ZCL_MANUFACTURER_CODE 0x1049
#define SL_ZIGBEE_AF_DEFAULT_RESPONSE_POLICY_ALWAYS

// All Enabled Clusters
#define ZCL_USING_BASIC_CLUSTER_SERVER
#define ZCL_USING_IDENTIFY_CLUSTER_SERVER
#define ZCL_USING_GROUPS_CLUSTER_SERVER
#define ZCL_USING_SCENES_CLUSTER_SERVER
#define ZCL_USING_ON_OFF_CLUSTER_SERVER
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_SERVER
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_CLIENT
#define ZCL_USING_OCCUPANCY_SENSING_CLUSTER_CLIENT
#define ZCL_USING_ZLL_COMMISSIONING_CLUSTER_SERVER

// Cluster Counts
#define SL_ZIGBEE_ZCL_BASIC_CLUSTER_SERVER_ENDPOINT_COUNT (1)
#define SL_ZIGBEE_ZCL_IDENTIFY_CLUSTER_SERVER_ENDPOINT_COUNT (1)
#define SL_ZIGBEE_ZCL_GROUPS_CLUSTER_SERVER_ENDPOINT_COUNT (1)
#define SL_ZIGBEE_ZCL_SCENES_CLUSTER_SERVER_ENDPOINT_COUNT (1)
#define SL_ZIGBEE_ZCL_ON_OFF_CLUSTER_SERVER_ENDPOINT_COUNT (1)
#define SL_ZIGBEE_ZCL_LEVEL_CONTROL_CLUSTER_SERVER_ENDPOINT_COUNT (1)
#define SL_ZIGBEE_ZCL_OTA_BOOTLOAD_CLUSTER_CLIENT_ENDPOINT_COUNT (1)
#define SL_ZIGBEE_ZCL_OCCUPANCY_SENSING_CLUSTER_CLIENT_ENDPOINT_COUNT (1)
#define SL_ZIGBEE_ZCL_ZLL_COMMISSIONING_CLUSTER_SERVER_ENDPOINT_COUNT (1)

// All Enabled Cluster Attributes
#define ZCL_USING_BASIC_CLUSTER_VERSION_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_APPLICATION_VERSION_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_STACK_VERSION_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_HW_VERSION_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_MANUFACTURER_NAME_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_MODEL_IDENTIFIER_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_DATE_CODE_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_POWER_SOURCE_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_GENERIC_DEVICE_CLASS_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_GENERIC_DEVICE_TYPE_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_PRODUCT_CODE_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_PRODUCT_URL_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_SW_BUILD_ID_ATTRIBUTE
#define ZCL_USING_BASIC_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE
#define ZCL_USING_IDENTIFY_CLUSTER_IDENTIFY_TIME_ATTRIBUTE
#define ZCL_USING_IDENTIFY_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE
#define ZCL_USING_GROUPS_CLUSTER_GROUP_NAME_SUPPORT_ATTRIBUTE
#define ZCL_USING_GROUPS_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE
#define ZCL_USING_SCENES_CLUSTER_SCENE_COUNT_ATTRIBUTE
#define ZCL_USING_SCENES_CLUSTER_CURRENT_SCENE_ATTRIBUTE
#define ZCL_USING_SCENES_CLUSTER_CURRENT_GROUP_ATTRIBUTE
#define ZCL_USING_SCENES_CLUSTER_SCENE_VALID_ATTRIBUTE
#define ZCL_USING_SCENES_CLUSTER_SCENE_NAME_SUPPORT_ATTRIBUTE
#define ZCL_USING_SCENES_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE
#define ZCL_USING_ON_OFF_CLUSTER_ON_OFF_ATTRIBUTE
#define ZCL_USING_ON_OFF_CLUSTER_GLOBAL_SCENE_CONTROL_ATTRIBUTE
#define ZCL_USING_ON_OFF_CLUSTER_ON_TIME_ATTRIBUTE
#define ZCL_USING_ON_OFF_CLUSTER_OFF_WAIT_TIME_ATTRIBUTE
#define ZCL_USING_ON_OFF_CLUSTER_START_UP_ON_OFF_ATTRIBUTE
#define ZCL_USING_ON_OFF_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_CURRENT_LEVEL_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_LEVEL_CONTROL_REMAINING_TIME_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_OPTIONS_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_ON_OFF_TRANSITION_TIME_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_ON_TRANSITION_TIME_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_OFF_TRANSITION_TIME_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_DEFAULT_MOVE_RATE_ATTRIBUTE
#define ZCL_USING_LEVEL_CONTROL_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_UPGRADE_SERVER_ID_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_FILE_OFFSET_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_IMAGE_UPGRADE_STATUS_ATTRIBUTE
#define ZCL_USING_OTA_BOOTLOAD_CLUSTER_CLUSTER_REVISION_CLIENT_ATTRIBUTE
#define ZCL_USING_OCCUPANCY_SENSING_CLUSTER_CLUSTER_REVISION_CLIENT_ATTRIBUTE
#define ZCL_USING_ZLL_COMMISSIONING_CLUSTER_CLUSTER_REVISION_SERVER_ATTRIBUTE

#define SL_ZIGBEE_AF_SUPPORT_COMMAND_DISCOVERY

/* Format: Zigbee Cluster Code, Zigbee Cluster Mfg Code, Matter Cluster Code, Matter Cluster Mfg Code, Zigbee Attribute Code, Zigbee Attribute Mfg Code, Zigbee Attribute Type Identifier, Matter Attribute Code, Matter Attribute Mfg Code, Matter Attribute Type Identifier */
#define GENERATED_MULTI_PROTOCOL_ATTRIBUTE_MAPPING \
{ \
  { 0x0000, 0x0000, 16, 0x0000, 0x0000, 16 }, /* 0, Zigbee Cluster: On/off, Matter Cluster: On/Off, Zigbee Attribute: on/off, Matter Attribute: OnOff */ \
  { 0x4003, 0x0000, 48, 0x4003, 0x0000, 48 }, /* 1, Zigbee Cluster: On/off, Matter Cluster: On/Off, Zigbee Attribute: start up on off, Matter Attribute: StartUpOnOff */ \
  { 0x0000, 0x0000, 32, 0x0000, 0x0000, 32 }, /* 2, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: current level, Matter Attribute: CurrentLevel */ \
  { 0x0001, 0x0000, 33, 0x0001, 0x0000, 33 }, /* 3, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: remaining time, Matter Attribute: RemainingTime */ \
  { 0x0002, 0x0000, 32, 0x0002, 0x0000, 32 }, /* 4, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: min level, Matter Attribute: MinLevel */ \
  { 0x0003, 0x0000, 32, 0x0003, 0x0000, 32 }, /* 5, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: max level, Matter Attribute: MaxLevel */ \
  { 0x0004, 0x0000, 33, 0x0004, 0x0000, 33 }, /* 6, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: current frequency, Matter Attribute: CurrentFrequency */ \
  { 0x0005, 0x0000, 33, 0x0005, 0x0000, 33 }, /* 7, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: min frequency, Matter Attribute: MinFrequency */ \
  { 0x0006, 0x0000, 33, 0x0006, 0x0000, 33 }, /* 8, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: max frequency, Matter Attribute: MaxFrequency */ \
  { 0x000F, 0x0000, 24, 0x000F, 0x0000, 24 }, /* 9, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: options, Matter Attribute: Options */ \
  { 0x0010, 0x0000, 33, 0x0010, 0x0000, 33 }, /* 10, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: on off transition time, Matter Attribute: OnOffTransitionTime */ \
  { 0x0011, 0x0000, 32, 0x0011, 0x0000, 32 }, /* 11, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: on level, Matter Attribute: OnLevel */ \
  { 0x0012, 0x0000, 33, 0x0012, 0x0000, 33 }, /* 12, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: on transition time, Matter Attribute: OnTransitionTime */ \
  { 0x0013, 0x0000, 33, 0x0013, 0x0000, 33 }, /* 13, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: off transition time, Matter Attribute: OffTransitionTime */ \
  { 0x0014, 0x0000, 32, 0x0014, 0x0000, 32 }, /* 14, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: default move rate, Matter Attribute: DefaultMoveRate */ \
  { 0x4000, 0x0000, 32, 0x4000, 0x0000, 32 }, /* 15, Zigbee Cluster: Level Control, Matter Cluster: Level Control, Zigbee Attribute: start up current level, Matter Attribute: StartUpCurrentLevel */ \
  { 0x0000, 0x0000, 41, 0x0000, 0x0000, 216 }, /* 16, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: local temperature, Matter Attribute: LocalTemperature */ \
  { 0x0001, 0x0000, 41, 0x0001, 0x0000, 216 }, /* 17, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: outdoor temperature, Matter Attribute: OutdoorTemperature */ \
  { 0x0002, 0x0000, 24, 0x0002, 0x0000, 24 }, /* 18, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: occupancy, Matter Attribute: Occupancy */ \
  { 0x0003, 0x0000, 41, 0x0003, 0x0000, 216 }, /* 19, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: abs min heat setpoint limit, Matter Attribute: AbsMinHeatSetpointLimit */ \
  { 0x0004, 0x0000, 41, 0x0004, 0x0000, 216 }, /* 20, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: abs max heat setpoint limit, Matter Attribute: AbsMaxHeatSetpointLimit */ \
  { 0x0005, 0x0000, 41, 0x0005, 0x0000, 216 }, /* 21, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: abs min cool setpoint limit, Matter Attribute: AbsMinCoolSetpointLimit */ \
  { 0x0006, 0x0000, 41, 0x0006, 0x0000, 216 }, /* 22, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: abs max cool setpoint limit, Matter Attribute: AbsMaxCoolSetpointLimit */ \
  { 0x0007, 0x0000, 32, 0x0007, 0x0000, 32 }, /* 23, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: pi cooling demand, Matter Attribute: PICoolingDemand */ \
  { 0x0008, 0x0000, 32, 0x0008, 0x0000, 32 }, /* 24, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: pi heating demand, Matter Attribute: PIHeatingDemand */ \
  { 0x0009, 0x0000, 24, 0x0009, 0x0000, 24 }, /* 25, Zigbee Cluster: Thermostat, Matter Cluster: Thermostat, Zigbee Attribute: HVAC system type configuration, Matter Attribute: HVACSystemTypeConfiguration */ \
  { 0x0000, 0x0000, 48, 0x0000, 0x0000, 48 }, /* 26, Zigbee Cluster: Thermostat User Interface Configuration, Matter Cluster: Thermostat User Interface Configuration, Zigbee Attribute: temperature display mode, Matter Attribute: TemperatureDisplayMode */ \
  { 0x0001, 0x0000, 48, 0x0001, 0x0000, 48 }, /* 27, Zigbee Cluster: Thermostat User Interface Configuration, Matter Cluster: Thermostat User Interface Configuration, Zigbee Attribute: keypad lockout, Matter Attribute: KeypadLockout */ \
  { 0x0002, 0x0000, 48, 0x0002, 0x0000, 48 }, /* 28, Zigbee Cluster: Thermostat User Interface Configuration, Matter Cluster: Thermostat User Interface Configuration, Zigbee Attribute: schedule programming visibility, Matter Attribute: ScheduleProgrammingVisibility */ \
  { 0x0000, 0x0000, 32, 0x0000, 0x0000, 32 }, /* 29, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: current hue, Matter Attribute: CurrentHue */ \
  { 0x0001, 0x0000, 32, 0x0001, 0x0000, 32 }, /* 30, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: current saturation, Matter Attribute: CurrentSaturation */ \
  { 0x0002, 0x0000, 33, 0x0002, 0x0000, 33 }, /* 31, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: remaining time, Matter Attribute: RemainingTime */ \
  { 0x0003, 0x0000, 33, 0x0003, 0x0000, 33 }, /* 32, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: current x, Matter Attribute: CurrentX */ \
  { 0x0004, 0x0000, 33, 0x0004, 0x0000, 33 }, /* 33, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: current y, Matter Attribute: CurrentY */ \
  { 0x0005, 0x0000, 48, 0x0005, 0x0000, 48 }, /* 34, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: drift compensation, Matter Attribute: DriftCompensation */ \
  { 0x0006, 0x0000, 66, 0x0006, 0x0000, 66 }, /* 35, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: compensation text, Matter Attribute: CompensationText */ \
  { 0x0007, 0x0000, 33, 0x0007, 0x0000, 33 }, /* 36, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color temperature, Matter Attribute: ColorTemperatureMireds */ \
  { 0x0008, 0x0000, 48, 0x0008, 0x0000, 48 }, /* 37, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color mode, Matter Attribute: ColorMode */ \
  { 0x000F, 0x0000, 24, 0x000F, 0x0000, 24 }, /* 38, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color control options, Matter Attribute: Options */ \
  { 0x0010, 0x0000, 32, 0x0010, 0x0000, 32 }, /* 39, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: number of primaries, Matter Attribute: NumberOfPrimaries */ \
  { 0x0011, 0x0000, 33, 0x0011, 0x0000, 33 }, /* 40, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 1 x, Matter Attribute: Primary1X */ \
  { 0x0012, 0x0000, 33, 0x0012, 0x0000, 33 }, /* 41, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 1 y, Matter Attribute: Primary1Y */ \
  { 0x0013, 0x0000, 32, 0x0013, 0x0000, 32 }, /* 42, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 1 intensity, Matter Attribute: Primary1Intensity */ \
  { 0x0015, 0x0000, 33, 0x0015, 0x0000, 33 }, /* 43, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 2 x, Matter Attribute: Primary2X */ \
  { 0x0016, 0x0000, 33, 0x0016, 0x0000, 33 }, /* 44, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 2 y, Matter Attribute: Primary2Y */ \
  { 0x0017, 0x0000, 32, 0x0017, 0x0000, 32 }, /* 45, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 2 intensity, Matter Attribute: Primary2Intensity */ \
  { 0x0019, 0x0000, 33, 0x0019, 0x0000, 33 }, /* 46, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 3 x, Matter Attribute: Primary3X */ \
  { 0x001A, 0x0000, 33, 0x001A, 0x0000, 33 }, /* 47, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 3 y, Matter Attribute: Primary3Y */ \
  { 0x001B, 0x0000, 32, 0x001B, 0x0000, 32 }, /* 48, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 3 intensity, Matter Attribute: Primary3Intensity */ \
  { 0x0020, 0x0000, 33, 0x0020, 0x0000, 33 }, /* 49, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 4 x, Matter Attribute: Primary4X */ \
  { 0x0021, 0x0000, 33, 0x0021, 0x0000, 33 }, /* 50, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 4 y, Matter Attribute: Primary4Y */ \
  { 0x0022, 0x0000, 32, 0x0022, 0x0000, 32 }, /* 51, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 4 intensity, Matter Attribute: Primary4Intensity */ \
  { 0x0024, 0x0000, 33, 0x0024, 0x0000, 33 }, /* 52, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 5 x, Matter Attribute: Primary5X */ \
  { 0x0025, 0x0000, 33, 0x0025, 0x0000, 33 }, /* 53, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 5 y, Matter Attribute: Primary5Y */ \
  { 0x0026, 0x0000, 32, 0x0026, 0x0000, 32 }, /* 54, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 5 intensity, Matter Attribute: Primary5Intensity */ \
  { 0x0028, 0x0000, 33, 0x0028, 0x0000, 33 }, /* 55, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 6 x, Matter Attribute: Primary6X */ \
  { 0x0029, 0x0000, 33, 0x0029, 0x0000, 33 }, /* 56, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 6 y, Matter Attribute: Primary6Y */ \
  { 0x002A, 0x0000, 32, 0x002A, 0x0000, 32 }, /* 57, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: primary 6 intensity, Matter Attribute: Primary6Intensity */ \
  { 0x0030, 0x0000, 33, 0x0030, 0x0000, 33 }, /* 58, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: white point x, Matter Attribute: WhitePointX */ \
  { 0x0031, 0x0000, 33, 0x0031, 0x0000, 33 }, /* 59, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: white point y, Matter Attribute: WhitePointY */ \
  { 0x0032, 0x0000, 33, 0x0032, 0x0000, 33 }, /* 60, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point r x, Matter Attribute: ColorPointRX */ \
  { 0x0033, 0x0000, 33, 0x0033, 0x0000, 33 }, /* 61, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point r y, Matter Attribute: ColorPointRY */ \
  { 0x0034, 0x0000, 32, 0x0034, 0x0000, 32 }, /* 62, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point r intensity, Matter Attribute: ColorPointRIntensity */ \
  { 0x0036, 0x0000, 33, 0x0036, 0x0000, 33 }, /* 63, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point g x, Matter Attribute: ColorPointGX */ \
  { 0x0037, 0x0000, 33, 0x0037, 0x0000, 33 }, /* 64, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point g y, Matter Attribute: ColorPointGY */ \
  { 0x0038, 0x0000, 32, 0x0038, 0x0000, 32 }, /* 65, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point g intensity, Matter Attribute: ColorPointGIntensity */ \
  { 0x003A, 0x0000, 33, 0x003A, 0x0000, 33 }, /* 66, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point b x, Matter Attribute: ColorPointBX */ \
  { 0x003B, 0x0000, 33, 0x003B, 0x0000, 33 }, /* 67, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point b y, Matter Attribute: ColorPointBY */ \
  { 0x003C, 0x0000, 32, 0x003C, 0x0000, 32 }, /* 68, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color point b intensity, Matter Attribute: ColorPointBIntensity */ \
  { 0x4000, 0x0000, 33, 0x4000, 0x0000, 33 }, /* 69, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: enhanced current hue, Matter Attribute: EnhancedCurrentHue */ \
  { 0x4001, 0x0000, 48, 0x4001, 0x0000, 48 }, /* 70, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: enhanced color mode, Matter Attribute: EnhancedColorMode */ \
  { 0x4002, 0x0000, 32, 0x4002, 0x0000, 32 }, /* 71, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color loop active, Matter Attribute: ColorLoopActive */ \
  { 0x4003, 0x0000, 32, 0x4003, 0x0000, 32 }, /* 72, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color loop direction, Matter Attribute: ColorLoopDirection */ \
  { 0x4004, 0x0000, 33, 0x4004, 0x0000, 33 }, /* 73, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color loop time, Matter Attribute: ColorLoopTime */ \
  { 0x4005, 0x0000, 33, 0x4005, 0x0000, 33 }, /* 74, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color loop start enhanced hue, Matter Attribute: ColorLoopStartEnhancedHue */ \
  { 0x4006, 0x0000, 33, 0x4006, 0x0000, 33 }, /* 75, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color loop stored enhanced hue, Matter Attribute: ColorLoopStoredEnhancedHue */ \
  { 0x400A, 0x0000, 25, 0x400A, 0x0000, 25 }, /* 76, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color capabilities, Matter Attribute: ColorCapabilities */ \
  { 0x400B, 0x0000, 33, 0x400B, 0x0000, 33 }, /* 77, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color temp physical min, Matter Attribute: ColorTempPhysicalMinMireds */ \
  { 0x400C, 0x0000, 33, 0x400C, 0x0000, 33 }, /* 78, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: color temp physical max, Matter Attribute: ColorTempPhysicalMaxMireds */ \
  { 0x400D, 0x0000, 33, 0x400D, 0x0000, 33 }, /* 79, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: couple color temp to level min-mireds, Matter Attribute: CoupleColorTempToLevelMinMireds */ \
  { 0x4010, 0x0000, 33, 0x4010, 0x0000, 33 } /* 80, Zigbee Cluster: Color Control, Matter Cluster: Color Control, Zigbee Attribute: start up color temperature mireds, Matter Attribute: StartUpColorTemperatureMireds */ \
}

#define GENERATED_MULTI_PROTOCOL_CLUSTER_MAPPING \
{ \
{ 0x0006, 0x0000, 0x0006, 0x0000, (sl_zigbee_matter_af_multi_protocol_attribute_metadata_t*)&multiProtocolAttributeMap[0], 2 }, /* Zigbee Cluster: On/off, Matter Cluster: On/Off */ \
{ 0x0008, 0x0000, 0x0008, 0x0000, (sl_zigbee_matter_af_multi_protocol_attribute_metadata_t*)&multiProtocolAttributeMap[2], 14 }, /* Zigbee Cluster: Level Control, Matter Cluster: Level Control */ \
{ 0x0201, 0x0000, 0x0201, 0x0000, (sl_zigbee_matter_af_multi_protocol_attribute_metadata_t*)&multiProtocolAttributeMap[16], 10 }, /* Zigbee Cluster: Thermostat, Matter Cluster: Thermostat */ \
{ 0x0204, 0x0000, 0x0204, 0x0000, (sl_zigbee_matter_af_multi_protocol_attribute_metadata_t*)&multiProtocolAttributeMap[26], 3 }, /* Zigbee Cluster: Thermostat User Interface Configuration, Matter Cluster: Thermostat User Interface Configuration */ \
{ 0x0300, 0x0000, 0x0300, 0x0000, (sl_zigbee_matter_af_multi_protocol_attribute_metadata_t*)&multiProtocolAttributeMap[29], 52 } /* Zigbee Cluster: Color Control, Matter Cluster: Color Control */ \
}

#endif // SILABS_AF_ENDPOINT_CONFIG