#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

// APIs present in project
#define SL_CATALOG_CLOCK_MANAGER_PRESENT
#define SL_CATALOG_GPIO_PRESENT
#define SL_CATALOG_HAL_SYSTEM_PRESENT
#define SL_CATALOG_INTERRUPT_MANAGER_PRESENT
#define SL_CATALOG_INTERRUPT_MANAGER_VECTOR_TABLE_IN_RAM_PRESENT
#define SL_CATALOG_SE_MANAGER_PRESENT
#define SL_CATALOG_SL_CORE_PRESENT

#endif // SL_COMPONENT_CATALOG_H
